# Generated by Django 3.1.12 on 2025-09-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(help_text='Full_name', max_length=50)),
                ('Email_Address', models.EmailField(help_text='Email', max_length=254)),
                ('Subject', models.CharField(help_text='Subject', max_length=50)),
                ('Message', models.CharField(help_text='Message', max_length=50)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('size', models.CharField(max_length=50)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('upload_by', models.EmailField(help_text='user_email', max_length=254, unique=True)),
            ],
            options={
                'db_table': 'DatasetUpload',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.CharField(max_length=100, null=True)),
                ('Review', models.CharField(max_length=225, null=True)),
                ('Sentiment', models.CharField(max_length=100, null=True)),
                ('Reviewer', models.EmailField(help_text='user_email', max_length=254, unique=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('user_email', models.EmailField(help_text='user_email', max_length=254, unique=True)),
                ('user_password', models.EmailField(help_text='user_password', max_length=50)),
                ('user_address', models.TextField(help_text='user_address', max_length=100)),
                ('user_contact', models.CharField(help_text='user_contact', max_length=15, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
