# Generated by Django 3.1.12 on 2025-09-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetupload',
            old_name='id',
            new_name='dataid',
        ),
    ]
