# Generated by Django 3.1.12 on 2025-09-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20250902_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetupload',
            name='file',
            field=models.FileField(upload_to='datasets/'),
        ),
        migrations.AlterField(
            model_name='datasetupload',
            name='upload_by',
            field=models.EmailField(help_text='user_email', max_length=254),
        ),
    ]
