# Generated by Django 3.1.12 on 2025-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20250902_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDatasetModel',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('dataset', models.FileField(upload_to='dataset/')),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upload_dataset',
            },
        ),
        migrations.DeleteModel(
            name='DatasetUpload',
        ),
    ]
