# Generated by Django 3.1.12 on 2025-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20250902_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatasetmodel',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
