# Generated by Django 3.1.12 on 2025-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_usermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
